from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String

from src.db.base import Base


class SkillRegistryModel(Base):
    """Persistent identity for a skill independent of the bootstrap seed."""

    __tablename__ = "skill_registry"

    # Seeded records retain their existing ``skill_*`` IDs. New records use a
    # UUID generated by the project's established model-ID convention.
    skill_id = Column(String(100), primary_key=True, default=lambda: str(uuid.uuid4()))
    canonical_name = Column(String(255), nullable=False)
    normalized_name = Column(String(255), nullable=False, unique=True, index=True)
    category = Column(String(150), nullable=True)
    source = Column(String(50), nullable=False, default="observed")
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class SkillRegistryAliasModel(Base):
    """Trusted alternate spellings mapped to a single registry identity."""

    __tablename__ = "skill_registry_aliases"

    id = Column(Integer, primary_key=True, autoincrement=True)
    skill_id = Column(String(100), ForeignKey("skill_registry.skill_id"), nullable=False, index=True)
    alias_name = Column(String(255), nullable=False)
    normalized_alias = Column(String(255), nullable=False, unique=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
