import pytest

from src.core.config import LLMSettings
from src.core.llm_service import GeminiProvider, LLMService, OpenAICompatibleProvider
from src.cv_extractor.llm_extractor import LLMExtractor


def test_llm_settings_defaults():
    settings = LLMSettings.load_from_env()
    assert settings.provider in ("gemini", "openai")
    assert settings.model_name is not None
    assert settings.temperature == 0.0
    assert settings.max_tokens >= 1024


def test_llm_provider_switching():
    # 1. Gemini configuration
    gemini_settings = LLMSettings(
        provider="gemini",
        api_key="test_gemini_key",
        model_name="gemini-1.5-pro"
    )
    svc_gemini = LLMService(gemini_settings)
    assert isinstance(svc_gemini.provider, GeminiProvider)
    assert svc_gemini.settings.model_name == "gemini-1.5-pro"

    # 2. OpenAI / Groq configuration
    openai_settings = LLMSettings(
        provider="openai",
        api_key="sk-test-openai-key",
        model_name="gpt-4o-mini",
        base_url="https://api.openai.com/v1"
    )
    svc_openai = LLMService(openai_settings)
    assert isinstance(svc_openai.provider, OpenAICompatibleProvider)
    assert svc_openai.settings.model_name == "gpt-4o-mini"
    assert svc_openai.provider.base_url == "https://api.openai.com/v1"

    # 3. Local Ollama / Custom gateway configuration
    ollama_settings = LLMSettings(
        provider="ollama",
        api_key=None,
        model_name="llama3.2:latest",
        base_url="http://localhost:11434/v1"
    )
    svc_ollama = LLMService(ollama_settings)
    assert isinstance(svc_ollama.provider, OpenAICompatibleProvider)
    assert svc_ollama.provider.base_url == "http://localhost:11434/v1"


def test_feature_layer_decoupled_from_llm():
    # Feature layer consumes LLMService via dependency injection
    mock_settings = LLMSettings(provider="gemini", api_key=None)
    mock_service = LLMService(mock_settings)

    # Feature layer uses centralized service without hardcoding API keys or models
    extractor = LLMExtractor(llm_service=mock_service)
    assert extractor.llm_service == mock_service

    # Offline/No-key fallback works cleanly
    extracted = extractor.extract_entities(
        full_text="John Doe\nEmail: john@example.com\nEDUCATION\nBSc Computer Science",
        sections={"header": "John Doe", "education": "BSc Computer Science"}
    )
    assert extracted["name"] == "John Doe"
    assert extracted["email"] == "john@example.com"


class TestRobustJSONParsing:
    """Test suite verifying robust JSON extraction without greedy regex crashes."""

    def test_generate_json_multiple_objects_no_extra_data_crash(self):
        """P1: A response containing two JSON objects must not crash with JSONDecodeError: Extra data."""
        mock_settings = LLMSettings(provider="gemini", api_key="dummy")
        svc = LLMService(mock_settings)
        raw_output = 'Here is the candidate profile: {"name": "Alice", "skills": ["Python"]} and metadata: {"model": "v1"}'
        svc.provider.generate_text = lambda prompt, system_prompt=None: raw_output

        result = svc.generate_json("Extract candidate")
        assert isinstance(result, dict)
        assert result["name"] == "Alice"
        assert result["skills"] == ["Python"]

    def test_generate_json_markdown_wrapped_with_commentary(self):
        """Markdown code fences with leading/trailing commentary are correctly parsed."""
        mock_settings = LLMSettings(provider="gemini", api_key="dummy")
        svc = LLMService(mock_settings)
        raw_output = 'Certainly! Here is the JSON:\n```json\n{"name": "Bob", "target_roles": ["Data Scientist"]}\n```\nHope this helps!'
        svc.provider.generate_text = lambda prompt, system_prompt=None: raw_output

        result = svc.generate_json("Extract candidate")
        assert isinstance(result, dict)
        assert result["name"] == "Bob"
        assert result["target_roles"] == ["Data Scientist"]

    def test_generate_json_array_payload(self):
        """JSON Array payloads are cleanly supported."""
        mock_settings = LLMSettings(provider="gemini", api_key="dummy")
        svc = LLMService(mock_settings)
        raw_output = 'Result list:\n[{"role": "Backend Engineer"}, {"role": "Fullstack Engineer"}]'
        svc.provider.generate_text = lambda prompt, system_prompt=None: raw_output

        result = svc.generate_json("Extract roles")
        assert isinstance(result, list)
        assert len(result) == 2
        assert result[0]["role"] == "Backend Engineer"

    def test_generate_json_trailing_comma_repair(self):
        """Trailing commas generated by LLMs are auto-repaired."""
        mock_settings = LLMSettings(provider="gemini", api_key="dummy")
        svc = LLMService(mock_settings)
        raw_output = '{"name": "Charlie", "skills": ["AI", "ML",], "active": true,}'
        svc.provider.generate_text = lambda prompt, system_prompt=None: raw_output

        result = svc.generate_json("Extract candidate")
        assert isinstance(result, dict)
        assert result["name"] == "Charlie"
        assert result["skills"] == ["AI", "ML"]
        assert result["active"] is True

    def test_generate_json_invalid_raises_value_error(self):
        """Completely invalid JSON raises a clear descriptive ValueError."""
        mock_settings = LLMSettings(provider="gemini", api_key="dummy")
        svc = LLMService(mock_settings)
        svc.provider.generate_text = lambda prompt, system_prompt=None: "Sorry, I cannot process this CV."

        with pytest.raises(ValueError, match="Failed to extract valid JSON"):
            svc.generate_json("Extract candidate")

    @pytest.mark.anyio
    async def test_generate_async_methods_non_blocking(self):
        """Asynchronous methods generate_text_async and generate_json_async run non-blockingly."""
        mock_settings = LLMSettings(provider="gemini", api_key="dummy")
        svc = LLMService(mock_settings)
        svc.provider.generate_text = lambda prompt, system_prompt=None: '{"name": "Async Candidate"}'

        text_result = await svc.generate_text_async("Extract name")
        assert 'Async Candidate' in text_result

        json_result = await svc.generate_json_async("Extract name")
        assert isinstance(json_result, dict)
        assert json_result["name"] == "Async Candidate"
